AWSTemplateFormatVersion: "2010-09-09"
Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: emr-default-role-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - '*'
            Effect: Allow
            Resource: '*'
            
  EMRCluster:
    Type: "AWS::EMR::Cluster"
    Properties:
      Name: "EMR Serverless Cluster"
      ReleaseLabel: "emr-6.2.0"
      Applications:
        - Name: "Hadoop"
      InstanceFleetConfigs:
        - InstanceTypeConfigs:
          - InstanceType: "m5.xlarge"
            BidPriceAsPercentageOfOnDemandPrice: 100
          LaunchSpecifications:
            SpotSpecification:
              TimeoutDurationMinutes: 120
              TimeToLiveTimeoutMinutes: 240
      AutoScalingPolicy:
        Constraints:
          MinCapacity: 2
          MaxCapacity: 20
      ScaleDownBehavior: TERMINATE_AT_TASK_COMPLETION
      EBSRootVolumeSize: 20
      VisibleToAllUsers: true
      JobFlowRole: !GetAtt IAMRole.Arn
      ServiceRole: !GetAtt IAMRole.Arn
      Steps:
        - Name: "Run custom script"
          ActionOnFailure: TERMINATE_CLUSTER
          HadoopJarStep:
            Jar: "command-runner.jar"
            Args:
              - "spark-submit"
              - "s3://mysparkawsbucket/spark-app.py"
Outputs:
  EMRClusterId:
    Value: !Ref EMRCluster
    Export:
      Name: EMRClusterId
