AWSTemplateFormatVersion: "2010-09-09"
Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: emr-default-role-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - '*'
            Effect: Allow
            Resource: '*'
            
  EMRCluster:
    Type: "AWS::EMR::Cluster"
    Properties:
      Name: "EMR Serverless Cluster"
      ReleaseLabel: "emr-6.2.0"
      Applications:
        - Name: "Hadoop"
      ScaleDownBehavior: TERMINATE_AT_TASK_COMPLETION
      JobFlowRole: !GetAtt IAMRole.Arn
      ServiceRole: !GetAtt IAMRole.Arn
      CoreInstanceType:
        Default: "r4.4xlarge"
        Description: "Instance type to be used for core instances."
        Type: "String"
      MasterInstanceType:
        Default: "r4.4xlarge"
        Description: "Instance type to be used for the master instance."
        Type: "String"
      LogUri:
        Default: "s3://mysparkawsbucket/"
        Description: "Must be a valid S3 URL"
        Type: "String"
      NumberOfCoreInstances:
        Default: 2
        Description: "Must be a valid number"
        Type: "Number"
      
      Steps:
        - Name: "Run custom script"
          ActionOnFailure: CONTINUE
          HadoopJarStep:
            Jar: "command-runner.jar"
            Args:
              - "spark-submit"
              - "s3://mysparkawsbucket/spark-app.py"
Outputs:
  EMRClusterId:
    Value: !Ref EMRCluster
    Export:
      Name: EMRClusterId
