AWSTemplateFormatVersion: '2010-09-09'
Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: emr-default-role-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - '*'
            Effect: Allow
            Resource: '*'
  EMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Instances:
        CoreInstanceGroup:
          InstanceType: "m5.xlarge"
          InstanceCount: 1
        MasterInstanceGroup:
          InstanceType: "m5.xlarge"
          InstanceCount: 1
        TaskInstanceGroups:
          - InstanceType: "m5.xlarge"
            InstanceCount: 1
      JobFlowRole: !GetAtt IAMRole.Arn
      ServiceRole: !GetAtt IAMRole.Arn
      Name: "MyEMRCluster"
      ReleaseLabel: "emr-6.2.0"
      Applications:
        - Name: "Spark"
      Configurations: []
      VisibleToAllUsers: true
      BootstrapActions: []
      Steps:
        - Name: "Run custom script"
          ActionOnFailure: CONTINUE
          HadoopJarStep:
            Jar: "command-runner.jar"
            Args:
              - "spark-submit"
              - "s3://mysparkawsbucket/spark-app.py"
