AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Instances:
        CoreInstanceGroup:
          InstanceType: "m5.xlarge"
          InstanceCount: 1
        MasterInstanceGroup:
          InstanceType: "m5.xlarge"
          InstanceCount: 1
        TaskInstanceGroups:
         - Name: "Task1"
           InstanceType: "m5.xlarge"
           InstanceCount: 1
      JobFlowRole: "arn:aws:iam::740062030037:role/EMR_DefaultRole"
      ServiceRole: "arn:aws:iam::740062030037:instance-profile/EMR_EC2_DefaultRole"
      Name: "MyEMRCluster"
      ReleaseLabel: "emr-6.2.0"
      Applications:
        - Name: "Spark"
      Configurations: []
      VisibleToAllUsers: true
      BootstrapActions: []
      Steps:
        - Name: "Run custom script"
          ActionOnFailure: CONTINUE
          HadoopJarStep:
            Jar: "command-runner.jar"
            Args:
              - "spark-submit"
              - "s3://mysparkawsbucket/spark-app.py"
