name: Upload to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deployment: [s3, cloudformation]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Upload spark-app.py to S3
      if: matrix.deployment == 's3'
      uses: docker://amazon/aws-cli:2.0.7
      with:
        args: s3 cp simple-pyspark-app.py s3://mysparkawsbucket/spark-app.py
        

    - name: Deploy CloudFormation stack
      if: matrix.deployment == 'cloudformation'
      uses: aws-actions/aws-cloudformation-github-deploy@v1.1.0
      with:
        template: cloudformation/cloudformation.yml
        name: my-cloudformation-stack
        capabilities: CAPABILITY_IAM




